[package]
name          = "maidsafe_utilities"
readme        = "README.md"
license       = "GPL-3.0"
version       = "0.1.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage      = "http://maidsafe.net"
repository    = "https://github.com/maidsafe/maidsafe_utilities"
description   = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"

[dev-dependencies]
time = "~0.1.34"
