[package]
name          = "maidsafe_utilities"
readme        = "README.md"
license       = "GPL-3.0"
version       = "0.1.5"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage      = "http://maidsafe.net"
repository    = "https://github.com/maidsafe/maidsafe_utilities"
description   = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"

[dependencies]
log             = "~0.3.3"
cbor            = "~0.3.16"
time            = "~0.1.34"
env_logger      = "~0.3.2"
rustc-serialize = "~0.3.16"
