[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "maidsafe_utilities"
readme = "README.md"
repository = "https://github.com/maidsafe/maidsafe_utilities"
version = "0.4.1"

[dependencies]
bincode = "~0.5.1"
log = "~0.3.5"
log4rs = "~0.3.3"
net2 = "~0.2.23"
quick-error = "1.0.0"
regex = "~0.1.58"
rustc-serialize = "~0.3.18"
toml = "~0.1.28"

[dependencies.clippy]
optional = true
version = "~0.0.54"

[dev-dependencies]
time = "~0.1.34"
