[package]
name = "maidsafe_utilities"
version = "0.1.5"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"
repository = "https://github.com/maidsafe/maidsafe_utilities"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
cbor = "~0.3.16"
clippy = {version = "~0.0.42", optional = true}
env_logger = "~0.3.2"
log = "~0.3.5"
rustc-serialize = "~0.3.18"
time = "~0.1.34"
