[appender.console]
kind = "console"

[appender.file]
kind = "file"
path = "main.log"

[appender.async_console]
kind = "async_console"

[appender.async_file]
kind = "async_file"
path = "main.log"

[root]
level = "trace"
appenders = ["console"]

# Per module logging rules
[[logger]]
name = "foo::bar::baz"
level = "warn"
appenders = ["file"]
