#[appender.async_console]
#kind = "async_console"

[appender.async_file]
kind = "async_file"
path = "main.log"

[appender.aysnc_web_socket]
kind = "async_web_socket"
server_url = "ws://127.0.0.1:59697"

[root]
level = "trace"
appenders = ["async_web_socket", "async_file"]
#appenders = ["async_web_socket", "async_file", "async_console"]
